# Generated by Django 6.1 on 2026-10-01 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("departamento", models.CharField(max_length=100)),
                ("salario_base", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_admissao", models.DateField()),
                ("ativo", models.BooleanField(default=True)),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funcionarios",
                        to="rh.cargo",
                    ),
                ),
            ],
        ),
    ]
